version: "2"
services:
    agent:
      image: wmucdev.azurecr.io/tviot-agent:2.17.3
      hostname: ${HOSTNAME}                             # Choose your own hostname
      container_name: uc_addon_teamviewer_iot_agent
      cpu_quota: 80000
      restart: unless-stopped
      environment:
        EULA_ACCEPTED: ${EULA_ACCEPTED}
        SERIAL_NUMBER_DOCKER_CONTAINER: ${HOSTNAME}     # Please fill in a serial number with at least 8 ASCII characters  
        ENABLE_APP_CONTROL: 1                           # Activate AppControl function on the agent
        APP_CONTROL_PORT: 80                            # Port for the web server to which the agent sholud connected
        APP_CONTROL_URL_SUFFIX:                         # Suffix for the AppControl Url
        APP_CONTROL_NAVIGATION_PANEL: 0                 # Enable AppControl navigation panel
        ENABLE_REMOTE_TERMINAL: 0                       # Activate Remote Terminal function on the agent
        ENABLE_APP_CONNECTED: 0                         # Activate Remote AppConnected (Port Forwarding) function on the agent You also need to add at least one port to APP_CONNECTED_ALLOWED_PORTS
        APP_CONNECTED_ALLOWED_PORTS: 443                # You can add more then one port to the variable. Please do it like this '22 443 80' 
        ASSIGNMENT_API_TOKEN: ${ASSIGNMENT_API_TOKEN}   # Assignment API tocken to assign the agent to an TeamViewer account. Please put the token betweeen '<TOKEN>' 
        ASSIGNMENT_GROUP_NAME: ${ASSIGNMENT_GROUP_NAME} # TeamViewer Computer and Contact group, where the agent should be part of it. Please put the name betweeen '<GROUP NAME>'
      network_mode: "host"
      volumes:
        - uc_addon_teamviewer_iot_agent:/var/persistent/teamviewer


    node-red:
      image: wmucdev.azurecr.io/uc-tviot-connector:1.0.3-1.0-alpha.1
      container_name: uc_addon_teamviewer_iot_connector 
      cpu_quota: 25000
      restart: unless-stopped
      environment:
        SENSOR_NAME: ${SENSOR_NAME}                     # Name of the sensor as it is visible in TeamViewer IoT portal        
        UPDATE_INTERVAL: ${UPDATE_INTERVAL}             # Interval at which metric values are updated in milli-seconds, must be 50ms or larger. 
        VAR_PREFIX: ${VAR_PREFIX}                       # Optional prefix which can be used to publish only a subset of variables. If set, only variables starting with VAR_PREFIX are published.
      network_mode: "host"
      depends_on: 
        - "agent"
      volumes:
        - uc_addon_teamviewer_iot_agent:/tviot
        - uc_addon_teamviewer_iot_connector:/data
