version: "2"

services:
  uc-addon-easyconnect-iiot:
    image: wmucrel.azurecr.io/uc-addon-easyconnect-iiot:0.9.0-beta.1 
    container_name: uc_addon_easyconnect_iiot 
    restart: unless-stopped
    cpu_quota: 25000
    network_mode: "host"
    volumes:
      - "uc_addon_easyconnect_iiot:/root/.local/share/wm-iiot-cloud-connector"

  uc-addon-telemetry:
    image: wmucrel.azurecr.io/uc-addon-telemetry:6.4.5-beta.1 
    container_name: uc_addon_telemetry  
    restart: unless-stopped
    cpu_quota: 25000
    network_mode: "host"
    volumes:
      - "uc_addon_telemetry:/root/.local/wm-iot"
